backend:
  name: github
  repo: Renatojr2/dev-blog 
  branch: master
  site_domain: programadormineiro.netlify.app/

publish_mode: editorial_workflow
media_folder: "static/assets/img"
public_folder: "assets/img"

collections:
  - name: "posts"
    label: "posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }